version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./api/Containerfile
    environment:
      - FLASK_APP=./api/__init__.py
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  ui:
    build:
      context: .
      dockerfile: ./ui/Containerfile
    volumes:
      - ./ui:/usr/src/app/
      - node_modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    depends_on:
      - api

volumes:
  postgres_data:
  node_modules:
