version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_data:
