---
version: 1
root:
  level: INFO
  handlers:
    - logstash
loggers:
  alembic:
    level: DEBUG
    handlers:
      - logstash
      - cloudwatch
    propogate: false
  sqlalchemy.engine:
    level: WARNING
    handlers:
      - logstash
      - cloudwatch
    propogate: false
  gumbaroo:
    level: INFO
    handlers:
      - logstash
      - cloudwatch
    propogate: false

handlers:
  logstash:
    class: logging.StreamHandler
    formatter: human_readable
    stream: ext://sys.stdout
  cloudwatch:
    "()": app.logging.cloudwatch_handler
    formatter: logstash

formatters:
  human_readable:
    format: "[%(asctime)s] [%(process)d] [%(thread)d] [%(name)s] [%(levelname)s] %(message)s"
  logstash:
    class: logstash_formater.LogstashFormatterV1
