---
name: PR Check

on:
  - pull_request

jobs:
  test:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Code
          uses: actions/checkout@v2

        - name: Perform CodeQL Analysis
          uses: github/codeql-action/analyze@v1