---
name: PR Check

on:
  - pull_request

jobs:
  test:
      runs-on: ubuntu-latest

      steps:
        - name: Check out repository code
          uses: actions/checkout@v2

        - name: run structure tests
          uses: plexsystems/container-structure-test-action@v0.1.0
          with:
            image: platform-changelog-ui:latest
            config: tests.yaml